Fix failing postgres tests by upgrading testcontainers (#52)
The GitHub Actions tests were failing with an `AttributeError: 'PostgresContainer' object has no attribute '_container'`. This was due to an old version of `testcontainers` being used.

This commit a new `testcontainers` version and updates the test code to use the new API.

Specifically, this commit:
- Upgrades `testcontainers` to `^4.4.0` in `pyproject.toml`.
- Updates the test files to use the new `testcontainers` API for accessing container credentials (e.g., `username` instead of `POSTGRES_USER`).
- Updates the `PostgresContainer` fixture to use a `with` statement for better resource management.